// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poke.Infra.Context;

namespace Poke.Infra.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Poke.Core.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HeldItem")
                        .HasColumnType("boolean")
                        .HasColumnName("held_item");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("item", "dbo");
                });

            modelBuilder.Entity("Poke.Core.Entities.Pokemon", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("FirstType")
                        .HasColumnType("integer")
                        .HasColumnName("first_type");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric(38,17)")
                        .HasColumnName("height");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<int>("SecondType")
                        .HasColumnType("integer")
                        .HasColumnName("second_type");

                    b.Property<string>("Species")
                        .HasColumnType("varchar")
                        .HasColumnName("species");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(38,17)")
                        .HasColumnName("weight");

                    b.HasKey("Number");

                    b.HasIndex("Id");

                    b.ToTable("pokemon", "dbo");
                });

            modelBuilder.Entity("Poke.Core.ValueObjects.AbstractEvolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ToNumber")
                        .HasColumnType("int")
                        .HasColumnName("to_number");

                    b.Property<int>("FromNumber")
                        .HasColumnType("int")
                        .HasColumnName("from_number");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("discriminator");

                    b.Property<int?>("EvolutionStone")
                        .HasColumnType("integer")
                        .HasColumnName("evolution_stone");

                    b.Property<int>("EvolutionType")
                        .HasColumnType("integer")
                        .HasColumnName("evolution_type");

                    b.Property<Guid?>("HeldItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("held_item_id");

                    b.Property<int?>("PokemonEvolutionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("pokemon_evolution_level");

                    b.HasKey("Id", "ToNumber", "FromNumber");

                    b.HasIndex("FromNumber");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("ToNumber");

                    b.ToTable("evolution", "dbo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AbstractEvolution");
                });

            modelBuilder.Entity("Poke.Core.ValueObjects.BaseStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("PokemonNumber")
                        .HasColumnType("int")
                        .HasColumnName("pokemon_number");

                    b.HasKey("Id");

                    b.HasIndex("PokemonNumber")
                        .IsUnique();

                    b.ToTable("base_stats", "dbo");
                });

            modelBuilder.Entity("Poke.Core.ValueObjects.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseFriendship")
                        .HasColumnType("integer")
                        .HasColumnName("base_friendship");

                    b.Property<int>("EVYeld")
                        .HasColumnType("integer")
                        .HasColumnName("ev_yeld");

                    b.Property<int>("GrowthRate")
                        .HasColumnType("integer")
                        .HasColumnName("growth_rate");

                    b.Property<int>("PokemonNumber")
                        .HasColumnType("int")
                        .HasColumnName("pokemon_number");

                    b.HasKey("Id");

                    b.HasIndex("PokemonNumber")
                        .IsUnique();

                    b.ToTable("training", "dbo");
                });

            modelBuilder.Entity("Poke.Core.ValueObjects.Evolutions.Evolution", b =>
                {
                    b.HasBaseType("Poke.Core.ValueObjects.AbstractEvolution");

                    b.HasDiscriminator().HasValue("Evolution");
                });

            modelBuilder.Entity("Poke.Core.ValueObjects.Evolutions.PreEvolution", b =>
                {
                    b.HasBaseType("Poke.Core.ValueObjects.AbstractEvolution");

                    b.HasDiscriminator().HasValue("PreEvolution");
                });

            modelBuilder.Entity("Poke.Core.ValueObjects.AbstractEvolution", b =>
                {
                    b.HasOne("Poke.Core.Entities.Pokemon", "PokemonEvolvesFrom")
                        .WithMany("PokemonsEvolveTo")
                        .HasForeignKey("FromNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poke.Core.Entities.Item", "HeldItem")
                        .WithMany()
                        .HasForeignKey("HeldItemId");

                    b.HasOne("Poke.Core.Entities.Pokemon", "PokemonEvolvesTo")
                        .WithMany("PokemonsEvolveFrom")
                        .HasForeignKey("ToNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeldItem");

                    b.Navigation("PokemonEvolvesFrom");

                    b.Navigation("PokemonEvolvesTo");
                });

            modelBuilder.Entity("Poke.Core.ValueObjects.BaseStats", b =>
                {
                    b.HasOne("Poke.Core.Entities.Pokemon", null)
                        .WithOne("BaseStats")
                        .HasForeignKey("Poke.Core.ValueObjects.BaseStats", "PokemonNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Poke.Core.Models.Point", "Attack", b1 =>
                        {
                            b1.Property<Guid>("BaseStatsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("attack");

                            b1.HasKey("BaseStatsId");

                            b1.ToTable("base_stats");

                            b1.WithOwner()
                                .HasForeignKey("BaseStatsId");
                        });

                    b.OwnsOne("Poke.Core.Models.Point", "Defense", b1 =>
                        {
                            b1.Property<Guid>("BaseStatsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("defense");

                            b1.HasKey("BaseStatsId");

                            b1.ToTable("base_stats");

                            b1.WithOwner()
                                .HasForeignKey("BaseStatsId");
                        });

                    b.OwnsOne("Poke.Core.Models.Point", "HitPoints", b1 =>
                        {
                            b1.Property<Guid>("BaseStatsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("hitpoints");

                            b1.HasKey("BaseStatsId");

                            b1.ToTable("base_stats");

                            b1.WithOwner()
                                .HasForeignKey("BaseStatsId");
                        });

                    b.OwnsOne("Poke.Core.Models.Point", "SpecialAttack", b1 =>
                        {
                            b1.Property<Guid>("BaseStatsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("special_attack");

                            b1.HasKey("BaseStatsId");

                            b1.ToTable("base_stats");

                            b1.WithOwner()
                                .HasForeignKey("BaseStatsId");
                        });

                    b.OwnsOne("Poke.Core.Models.Point", "SpecialDefense", b1 =>
                        {
                            b1.Property<Guid>("BaseStatsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("special_defense");

                            b1.HasKey("BaseStatsId");

                            b1.ToTable("base_stats");

                            b1.WithOwner()
                                .HasForeignKey("BaseStatsId");
                        });

                    b.OwnsOne("Poke.Core.Models.Point", "Speed", b1 =>
                        {
                            b1.Property<Guid>("BaseStatsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("speed");

                            b1.HasKey("BaseStatsId");

                            b1.ToTable("base_stats");

                            b1.WithOwner()
                                .HasForeignKey("BaseStatsId");
                        });

                    b.Navigation("Attack");

                    b.Navigation("Defense");

                    b.Navigation("HitPoints");

                    b.Navigation("SpecialAttack");

                    b.Navigation("SpecialDefense");

                    b.Navigation("Speed");
                });

            modelBuilder.Entity("Poke.Core.ValueObjects.Training", b =>
                {
                    b.HasOne("Poke.Core.Entities.Pokemon", null)
                        .WithOne("Training")
                        .HasForeignKey("Poke.Core.ValueObjects.Training", "PokemonNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Poke.Core.Entities.Pokemon", b =>
                {
                    b.Navigation("BaseStats");

                    b.Navigation("PokemonsEvolveFrom");

                    b.Navigation("PokemonsEvolveTo");

                    b.Navigation("Training");
                });
#pragma warning restore 612, 618
        }
    }
}
